//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLGenerator {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLGenerator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;sgbd type=&quot;SQLServer&quot;&gt;
        ///	&lt;commands&gt;
        ///		&lt;command type=&quot;select&quot;&gt;
        ///			&lt;select&gt;SELECT&lt;/select&gt;	
        ///			&lt;distinct&gt;DISTINCT&lt;/distinct&gt;			
        ///			&lt;all&gt;*&lt;/all&gt;
        ///			&lt;column&gt;${V1} AS ${V2}&lt;/column&gt;
        ///			&lt;from&gt;FROM ${V1}&lt;/from&gt;
        ///			&lt;join&gt;INNER JOIN ${V1} ON 0 = 0 &lt;and&gt;AND ${V1} = ${V2}&lt;/and&gt;&lt;/join&gt;
        ///			&lt;where&gt;WHERE ${V1} = ${V2}&lt;/where&gt;
        ///			&lt;and&gt;AND ${V1} = ${V2}&lt;/and&gt;
        ///			&lt;orderby&gt;ORDER BY 
        ///				&lt;asc&gt;${V1} ASC&lt;/asc&gt;
        ///				&lt;desc&gt;${V1} DESC&lt;/desc&gt;
        ///			&lt;/orderby&gt;
        ///			&lt;groupby&gt;GROUP BY &lt;item&gt;${V1}&lt;/item&gt;&lt;/groupby&gt;
        ///			&lt;top&gt;LIMI [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string PostgreSQLSchema {
            get {
                return ResourceManager.GetString("PostgreSQLSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;sgbd type=&quot;SQLServer&quot;&gt;
        ///	&lt;commands&gt;
        ///		&lt;command type=&quot;select&quot;&gt;
        ///			&lt;select&gt;SELECT&lt;/select&gt;	
        ///			&lt;distinct&gt;DISTINCT&lt;/distinct&gt;			
        ///			&lt;top&gt;TOP ${V1}&lt;/top&gt;
        ///			&lt;all&gt;*&lt;/all&gt;
        ///			&lt;column&gt;${V1} AS ${V2}&lt;/column&gt;
        ///			&lt;from&gt;FROM ${V1}&lt;/from&gt;
        ///			&lt;join&gt;INNER JOIN ${V1} ON 0 = 0 &lt;and&gt;AND ${V1} = ${V2}&lt;/and&gt;&lt;/join&gt;
        ///			&lt;where&gt;WHERE ${V1} = ${V2}&lt;/where&gt;
        ///			&lt;and&gt;AND ${V1} = ${V2}&lt;/and&gt;
        ///			&lt;orderby&gt;
        ///				ORDER BY
        ///				&lt;asc&gt;${V1} ASC&lt;/asc&gt;
        ///				&lt;desc&gt;${V1} DESC&lt;/desc&gt;
        ///			&lt;/orderby&gt;
        ///			&lt;groupby&gt;
        ///				GROUP BY &lt;item&gt; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SQLServerSchema {
            get {
                return ResourceManager.GetString("SQLServerSchema", resourceCulture);
            }
        }
    }
}
